<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>powerbi-modeling-mcp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.json" />
    <EmbeddedResource Include="appsettings.json" LogicalName="appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PowerBIModelingMCP.Library\PowerBIModelingMCP.Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="1.2.0" />
    <PackageReference Include="ModelContextProtocol.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageReference Include="Microsoft.AnalysisServices" Version="19.114.8" />
    <PackageReference Include="Microsoft.AnalysisServices.AdomdClient" Version="19.114.8" />
    <PackageReference Include="Azure.Core" Version="1.50.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>
</Project>
